name: "Worker: Step 97 - Cleanup Old Container Images"
on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

env:
  MIN_VERSIONS_TO_KEEP: 10

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required for deleting packages
      contents: read
    strategy:
      matrix:
        # Images produced by the 04-03-0*-build-ghcr-container* workflows
        package-name:
          - 'openmetadata-db'
          - 'openmetadata-server'
          - 'openmetadata-ingestion'
          - 'openmetadata-elasticsearch'
      fail-fast: false
    steps:
      - name: Delete old versions of ${{ matrix.package-name }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ matrix.package-name }}
          keep-n-untagged: ${{ env.MIN_VERSIONS_TO_KEEP }}
          token: ${{ secrets.GITHUB_TOKEN }}
