name: "Worker: Copy Mirror to Work Repo"

on:
  workflow_run:
    workflows: ["Worker: Mirror 3rd Party to Local"]
    types:
      - completed
  workflow_dispatch:
  # schedule:
  #   - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "FG_DOMAIN: ${{ vars.FG_DOMAIN }}"

      - uses: actions/checkout@v3
        with:
          repository: Jason-Clark-FG/OpenMetadata-Mirror
          # path: OpenMetadata
          fetch-depth: 0
          # token: $${{ secrets.GIT_TOKEN }}

      - name: Perform Modification
        run: |
          git config --global user.email "${GITHUB_ACTOR}@${FG_DOMAIN}"
          git config --global user.name "${GITHUB_ACTOR}"
          git status
          git pull
          git switch "$RELEASE_BRANCH"
          git status
          git switch -c "${RELEASE_BRANCH}-FG"
          src/openmetadata-modify-compose.sh docker/docker-compose-quickstart/docker-compose.yml
          git status
          git add docker/docker-compose-quickstart/docker-compose.yml
          git commit -m "chore: Modify docker/docker-compose-quickstart/docker-compose.yml"
          git push -u origin "${RELEASE_BRANCH}-FG"
          git status

      - name: mirror-repository
        # You may pin to the exact commit or the version.
        # uses: yesolutions/mirror-action@082a9611ed4b64c796245a62b34584ee2ded6833
        # uses: yesolutions/mirror-action@v0.6.0
        uses: yesolutions/mirror-action@master
        with:
          # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
          REMOTE_NAME: 'OpenMetadata-Mirror'
          # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
          REMOTE: 'git@github.com:Jason-Clark-FG/OpenMetadata-FG.git'
          # Username for remote repository
          #GIT_USERNAME: # optional
          # The git https password or token for the remote repository
          #GIT_PASSWORD: # optional
          # The ssh private key for writing to the remote repository, if using ssh
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }} # optional
          # The ssh public key for writing to the remote repository. Normally, not required at all
          GIT_SSH_PUBLIC_KEY: ${{ secrets.GIT_SSH_PUBLIC_KEY }} # optional
          # The contents of a SSH known_hosts file for host key verification
          # GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }} # optional
          # if true, skips host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS
          GIT_SSH_NO_VERIFY_HOST: "true" # optional, default is false
          # Push all refs instead of just the current branch
          #PUSH_ALL_REFS: # optional, default is true
          # The arugments to use when pushing the repository
          #GIT_PUSH_ARGS: # optional, default is --tags --force --prune
          # set to "true" to enable debug mode
          DEBUG: "true" # optional, default is false
