name: "Worker: Modify Work Repo"

on:
  workflow_run:
    workflows: ["Worker: Mirror Copy to Work Repo"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Show Info
      - name: "Show: Info"
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "FG_USER: ${{ vars.FG_USER }}"
          echo "FG_USERNAME: ${{ vars.FG_USERNAME }}"
          echo "FG_DOMAIN: ${{ vars.FG_DOMAIN }}"
          echo "FG_COMPOSE_TARGET: ${{ vars.FG_COMPOSE_TARGET }}"
          ls -laR ${GITHUB_WORKSPACE}
          ls -la ${GITHUB_WORKSPACE}/../
          ls -la ${GITHUB_WORKSPACE}/../../
          env | sort

      # Checkout our local mirror
      - uses: actions/checkout@v3
        with:
          repository: Jason-Clark-FG/OpenMetadata-FG
          fetch-depth: 0

      # Show Info
      - name: "Show: Info"
        run: |
          ls -la ${GITHUB_WORKSPACE}/
          ls -la ${GITHUB_WORKSPACE}/../
          ls -la ${GITHUB_WORKSPACE}/../../
          env | sort

      # Modify the target docker-conpose file
      - name: Perform Modification
        run: |
          git config --global user.email "${{ vars.FG_USERNAME }}@${{ vars.FG_DOMAIN }}"
          git config --global user.name "${{ vars.FG_USER }}"
          git status
          git pull
          git switch "${{ vars.RELEASE_BRANCH }}"
          git status
          git switch -c "${{ vars.RELEASE_BRANCH }}-FG"
          set -x
          which yq >/dev/null 2>&1;echo $?
          top_level_name=$(yq ".name" ${{ vars.FG_COMPOSE_TARGET }})
          if [[ ${top_level_name} == null ]];then echo "Adding top-level name";yq -i ".name = \"${compose_top_level_name}\"" ${{ vars.FG_COMPOSE_TARGET }};fi
          key_list=$(yq '.services | keys' ${{ vars.FG_COMPOSE_TARGET }} | cut -c '2-')
          for key in ${key_list};do restart_value=$(yq ".services.${key}.restart" ${{ vars.FG_COMPOSE_TARGET }});if [[ $restart_value == null ]];then echo "Adding restart to ${key}";yq -i ".services.${key}.restart = \"always\"" ${{ vars.FG_COMPOSE_TARGET }};fi;done
          set +x
          git status
          git add ${{ vars.FG_COMPOSE_TARGET }}
          git commit -m "chore: Modify docker/docker-compose-quickstart/docker-compose.yml"
          git push --set-upstream origin "${{ vars.RELEASE_BRANCH }}-FG"
          git status
