name: "Worker: Scan Containers"

on:
  workflow_run:
    workflows: ["Worker: Modify Work Repo"]
    types:
      - completed
  workflow_dispatch:

env:
  IMAGE_REGISTRY_1: docker.getcollate.io
  IMAGE_REGISTRY_2: docker.elastic.co
  IMAGE_OWNER_1: openmetadata
  IMAGE_OWNER_2: elasticsearch
  IMAGE_NAME_1: db
  IMAGE_NAME_2: ingestion
  IMAGE_NAME_3: server
  IMAGE_NAME_4: elasticsearch
  IMAGE_TAG_1: "1.1.4"
  IMAGE_TAG_2: "7.16.3"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write

    steps:
    # Checkout
    - name: Checkout Self
      uses: actions/checkout@v4
      # with:
      #   path: "self"

    # Ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env
    # - name: Additional Variables
    #   run: |
    #     echo "IMAGE_NAME=${{ secrets.DOCKER_USER }}/${{ env.IMAGE_BASENAME }}" >> $GITHUB_ENV
    #     # "IMAGE_TAG_2=$(yq '(.services.elasticsearch.image | split(":"))[1]' ${{ vars.FG_COMPOSE_TARGET }})" >> $GITHUB_ENV

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lDR ${GITHUB_WORKSPACE} | grep ':$'
        env | sort

    # Docker Buildx
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lDR ${GITHUB_WORKSPACE}/../ | grep ':$'
        env | sort

    - name: "Mend: Scan Images"
      id: mend-cli-scan-1
      if: ${{ github.event_name != 'pull_request_target' }}
      run: |
        curl -fsSL https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.PROD_RELEASE_BRANCH }}"
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_1 }}.sarif --format sarif --no-color --no-progress
        fi
        mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_1 }}.sarif --format sarif --no-color --no-progress
        echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.PROD_RELEASE_BRANCH }}"
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_3 }}.sarif --format sarif --no-color --no-progress
        fi
        mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_3 }}.sarif --format sarif --no-color --no-progress
        echo "Scanning ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ env.IMAGE_TAG_2 }}"
        if [[ ${{ vars.DEV_ES_RELEASE_BRANCH }} != ${{ vars.PROD_ES_RELEASE_BRANCH }} ]];then
          mend image ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.DEV_ES_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_4 }}.sarif --format sarif --no-color --no-progress
        fi
        mend image ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.PROD_ES_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_4 }}.sarif --format sarif --no-color --no-progress
        echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.PROD_RELEASE_BRANCH }}"
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_2 }}.sarif --format sarif --no-color --no-progress
        fi
        mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_2 }}.sarif --format sarif --no-color --no-progress
      env:
        MEND_URL: ${{ vars.MEND_URL }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lR ${GITHUB_WORKSPACE}

    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 1
    #   id: sarif-multitool-1
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_1 }}.sarif'
    # # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 2
    #   id: sarif-multitool-2
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_2 }}.sarif'
    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 3
    #   id: sarif-multitool-3
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_3 }}.sarif'
    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 4
    #   id: sarif-multitool-4
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_4 }}.sarif'

    # # Currently mend image outputs invalid SARIF, so we will skip this
    # # Ref: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions
    # - name: "Mend: Upload SARIF result 1"
    #   id: upload-sarif-1
    #   if: ${{ github.event_name != 'pull_request_target' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     category: mend-sca-${{ env.IMAGE_NAME_1 }}
    #     sarif_file: './reports/${{ env.IMAGE_NAME_1 }}.sarif'
    #     wait-for-processing: false
    #     # checkout_path: "self"
    # - name: "Mend: Upload SARIF result 2"
    #   id: upload-sarif-2
    #   if: ${{ github.event_name != 'pull_request_target' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     category: mend-sca-${{ env.IMAGE_NAME_2 }}
    #     sarif_file: './reports/${{ env.IMAGE_NAME_2 }}.sarif'
    #     wait-for-processing: false
    #     # checkout_path: "self"
    # - name: "Mend: Upload SARIF result 3"
    #   id: upload-sarif-3
    #   if: ${{ github.event_name != 'pull_request_target' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     category: mend-sca-${{ env.IMAGE_NAME_3 }}
    #     sarif_file: './reports/${{ env.IMAGE_NAME_3 }}.sarif'
    #     wait-for-processing: false
    #     # checkout_path: "self"
    # - name: "Mend: Upload SARIF result 4"
    #   id: upload-sarif-4
    #   if: ${{ github.event_name != 'pull_request_target' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     category: mend-sca-${{ env.IMAGE_NAME_4 }}
    #     sarif_file: './reports/${{ env.IMAGE_NAME_4 }}.sarif'
    #     wait-for-processing: false
    #     # checkout_path: "self"
