name: "Worker: Step 4.1 - Scan Containers"

on:
  workflow_run:
    workflows: ["Worker: Step 3 - Modify Work Repo Matrix"]
    types:
      - completed
  workflow_dispatch:

env:
  IMAGE_REGISTRY_1: docker.getcollate.io
  IMAGE_REGISTRY_2: docker.elastic.co
  IMAGE_OWNER_1: openmetadata
  IMAGE_OWNER_2: elasticsearch
  IMAGE_NAME_1: db
  IMAGE_NAME_2: ingestion
  IMAGE_NAME_3: server
  IMAGE_NAME_4: elasticsearch
  IMAGE_TAG_1: "1.1.6"
  IMAGE_TAG_2: "7.16.3"
  SCAN_RETRIES: 4
  REPORTS_OUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write

    steps:
    # Checkout
    - name: Checkout Self
      uses: actions/checkout@v4
      # with:
      #   path: "self"

    # Ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env
    # - name: Additional Variables
    #   run: |
    #     echo "IMAGE_NAME=${{ secrets.DOCKER_USER }}/${{ env.IMAGE_BASENAME }}" >> $GITHUB_ENV
    #     # "IMAGE_TAG_2=$(yq '(.services.elasticsearch.image | split(":"))[1]' ${{ vars.FG_COMPOSE_TARGET }})" >> $GITHUB_ENV

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lDR ${GITHUB_WORKSPACE} | grep ':$'
        env | sort

    # Docker Buildx
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lDR ${GITHUB_WORKSPACE}/../ | grep ':$'
        env | sort

    - name: "Mend: Scan Images"
      id: mend-cli-scan-1
      if: ${{ github.event_name != 'pull_request_target' }}
      shell: bash {0}
      run: |
        # Install Mend
        curl -fsSL https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        mend version
        # Image 1 - DEV
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
            echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.DEV_RELEASE_BRANCH }}"
            mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_1 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
            RESULT=$?
            (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
          done
        fi
        # Image 1 - PRD
        for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
          echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.PROD_RELEASE_BRANCH }}"
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_1 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_1 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
          RESULT=$?
          (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
        done
        # Image 2 - DEV
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
            echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.DEV_RELEASE_BRANCH }}"
            mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_3 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
            RESULT=$?
            (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
          done
        fi
        # Image 2 - PRD
        for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
          echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.PROD_RELEASE_BRANCH }}"
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_3 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_3 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
          RESULT=$?
          (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
        done
        # Image 3 - DEV
        if [[ ${{ vars.DEV_ES_RELEASE_BRANCH }} != ${{ vars.PROD_ES_RELEASE_BRANCH }} ]];then
          for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
            echo "Scanning ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.DEV_ES_RELEASE_BRANCH }}"
            mend image ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.DEV_ES_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_4 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
            RESULT=$?
            (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
          done
        fi
        # Image 3 -PRD
        for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
          echo "Scanning ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.PROD_ES_RELEASE_BRANCH }}"
          mend image ${{ env.IMAGE_REGISTRY_2 }}/${{ env.IMAGE_OWNER_2 }}/${{ env.IMAGE_NAME_4 }}:${{ vars.PROD_ES_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_4 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
          RESULT=$?
          (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
        done
        # Image 4 - DEV
        if [[ ${{ vars.DEV_RELEASE_BRANCH }} != ${{ vars.PROD_RELEASE_BRANCH }} ]];then
          for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
            echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.DEV_RELEASE_BRANCH }}"
            mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.DEV_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_2 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
            RESULT=$?
            (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
          done
        fi
        # Image 4 - PRD
        for ((tries=1;tries <= ${{ env.SCAN_RETRIES }};tries++));do
          echo "Scanning ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.PROD_RELEASE_BRANCH }}"
          mend image ${{ env.IMAGE_REGISTRY_1 }}/${{ env.IMAGE_OWNER_1 }}/${{ env.IMAGE_NAME_2 }}:${{ vars.PROD_RELEASE_BRANCH }} --filename ./reports/${{ env.IMAGE_NAME_2 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif --format sarif --no-color --no-progress
          RESULT=$?
          (( $RESULT == 0 )) && break 1 || echo "Trying again ... "
        done
      env:
        MEND_URL: ${{ vars.MEND_URL }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}

    # Show Info
    - name: "Show: Info"
      run: |
        ls -lR ${GITHUB_WORKSPACE}

    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 1
    #   id: sarif-multitool-1
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_1 }}.sarif'
    # # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 2
    #   id: sarif-multitool-2
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_2 }}.sarif'
    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 3
    #   id: sarif-multitool-3
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_3 }}.sarif'
    # # Ref: https://github.com/microsoft/sarif-actions
    # - name: SARIF Multitool 4
    #   id: sarif-multitool-4
    #   uses: microsoft/sarif-actions@v0.1
    #   with:
    #     # Command to be sent to SARIF Multitool
    #     command: 'validate ${GITHUB_WORKSPACE}/reports/${{ env.IMAGE_NAME_4 }}.sarif'

    # Currently mend image outputs invalid SARIF, so we will skip this
    # Ref: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions
    - name: "Mend: Upload SARIF result 1d"
      id: upload-sarif-1d
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_1 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_1 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 1p"
      id: upload-sarif-1p
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_1 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_1 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 2d"
      id: upload-sarif-2d
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_2 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_2 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 2p"
      id: upload-sarif-2p
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_2 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_2 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 3d"
      id: upload-sarif-3d
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_3 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_3 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 3p"
      id: upload-sarif-3p
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_3 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_3 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 4d"
      id: upload-sarif-4d
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_4 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_4 }}-${{ vars.DEV_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"
    - name: "Mend: Upload SARIF result 4p"
      id: upload-sarif-4p
      if: ${{ github.event_name != 'pull_request_target' && env.REPORTS_OUT == 'true' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: mend-sca-${{ env.IMAGE_NAME_4 }}
        sarif_file: './reports/${{ env.IMAGE_NAME_4 }}-${{ vars.PROD_RELEASE_BRANCH }}.sarif'
        wait-for-processing: false
        # checkout_path: "self"

