name: "Worker: Step 0 - Update Latest Version"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 6'

jobs:
  update_latest:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          LATEST_RELEASE=$(curl -fSsL -X GET https://api.github.com/repos/open-metadata/OpenMetadata/releases/latest | jq -r '.target_commitish')
          echo "LATEST_RELEASE: ${LATEST_RELEASE}"
          echo "Ouputting Action Variables:"
          curl -fSsL -X GET -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ env.MY_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/variables
          curl -fSsL -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ env.MY_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/variables/OM_LATEST_RELEASE -d "{\"name\":\"OM_LATEST_RELEASE\",\"value\":\"${LATEST_RELEASE}\"}"
          # gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/variables

